email: "randolphl@uthscsa.edu"

# -----------------------
# DNA ARCHIVE SEARCH
# -----------------------
dna_archive_search:
  database: gse
  retmax: 500
  query: >
    (bronchopulmonary dysplasia OR BPD) AND
    (Expression profiling by array OR microarray OR "gene expression profiling") AND
    Homo sapiens[Organism] AND
    (neonate OR newborn OR infant OR preterm OR premature OR "extremely low gestational age")

# -----------------------
# RNA ARCHIVE SEARCH
# -----------------------
rna_archive_search:
  database: gse
  retmax: 500
  query: >
    (bronchopulmonary dysplasia OR BPD) AND
    (RNA-seq OR RNAseq OR "Expression profiling by high throughput sequencing") AND
    Homo sapiens[Organism] AND
    (neonate OR newborn OR infant OR preterm OR premature OR "extremely low gestational age")

# -----------------------
# DNA WEEKLY SEARCH
# -----------------------
dna_weekly_search:
  database: gse
  retmax: 500
  reldate: 730
  query: >
    (bronchopulmonary dysplasia OR BPD) AND
    (Expression profiling by array OR microarray OR "gene expression profiling") AND
    Homo sapiens[Organism] AND
    (neonate OR newborn OR infant OR preterm OR premature OR "extremely low gestational age")

# -----------------------
# RNA WEEKLY SEARCH
# -----------------------
rna_weekly_search:
  database: gse
  retmax: 500
  reldate: 730
  query: >
    (bronchopulmonary dysplasia OR BPD) AND
    (RNA-seq OR RNAseq OR "Expression profiling by high throughput sequencing") AND
    Homo sapiens[Organism] AND
    (neonate OR newborn OR infant OR preterm OR premature OR "extremely low gestational age")
