case_patterns:
  - bpd
  - mild
  - moderate
  - severe
  - "bpd case"
  - "bronchopulmonary dysplasia"
  - sepsis
  - "clinical sepsis"
  - "Confirmed late-onset sepsis"
  - septic
  - disease
  - treated
  - tumor
  - Inf

control_patterns:
  - control
  - healthy
  - normal
  - untreated
  - uninfected
  - "uninfected chorio"
  - nobpd
  - nosepsis
  - nonbpd
  - none
  - "Possible late-onset sepsis"
  - "No late-onset sepsis"
  - "no_bpd"
  - "bpd_control"
  - "no bpd"
  - "non-bpd"
  - "bpd: severe"
  - "no sepsis"
  - "non-septic"
  - "no lung disease"
  - Sus
  - NEC
  - Vir

remove_pattern:
  - mirna
  - microrna
  - scramble
  - inhibtor
  - transfection
