# config

analysis:
  modalities:
    DNA: true
    RNA: true

  use_DEG: false

  inputs:
    dna_gse_file: "miner/outputs/dna_gse_ids.json"
    rna_gse_file: "miner/outputs/rna_gse_ids.json"

  forestplot:
    boxsize: 0.4
    clip:
      - 0.1
      - 10
    xticks:
      - 0.1
      - 0.5
      - 1
      - 2
      - 5
      - 10
    xlog: TRUE
    zero: 1
    graphwidth: 0.5

    colgap: 6
    lineheight: 6

    colors:
      box: "royalblue"
      line: "darkblue"
      summary: "royalblue"

    text_gp:
      ticks:
        cex: 1.3
      xlab:
        cex: 1.5

    zebrastyle: "#EFEFEF"
